context:
  version: "8.0.0"

package:
  name: hexo
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/hexo/-/hexo-${{ version }}.tgz
  sha256: 7a750d4ff5577e09aa81a8379b2ec86e785eb03772cd98ce499f1b233b6e3190

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - hexo --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A fast, simple & powerful blog framework, powered by Node.js.
  homepage: https://github.com/hexojs/hexo
  repository: https://github.com/hexojs/hexo

extra:
  recipe-maintainers:
    - danielnachun
